#!/bin/bash

target="unittest"

# directories are found by: `find . -maxdepth 2 -type d -name '[^\.]*'`
# we may append a _module_ by adding another directory for the search
# root of find
modules="../common ../src/system ../src/reader ../src/numeric ../src/misc ../src/algorithm"

additions=""

# append any needed libraries to ${libs}
# libs="mylib ${libs}"
