#!/bin/bash

target="unittest"

# directories are found by: `find . -maxdepth 2 -type d -name '[^\.]*'`
# we may append a _module_ by adding another directory for the search
# root of find
modules="../common ../src/reader ../src/misc ../src/numeric"

additions="../src/system/object.cc ../src/system/tuple.cc ../src/system/vector.cc"

# append any needed libraries to ${libs}
# libs="mylib ${libs}"
